version: '3'
services:
  eureka-service:
    build: eureka-service/
    hostname: eureka-service
    ports:
      - "8761:8761"
    networks:
      - default-network

  commonapi:
    build: commonapi/
    hostname: commonapi
    ports:
      - "8081:8081"
    networks:
      - default-network

  radar-service:
    build: radar-service/
    hostname: radar-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-service
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka
    networks:
      - default-network

  gateway:
    build: gateway/
    hostname: gateway
    ports:
      - "9999:9999"
    depends_on:
      - eureka-service
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka
    networks:
      - default-network

networks:
  default-network:
    driver: bridge